branch-defaults:
  master:
    environment: codeforrva-prod
global:
  application_name: codeforrva.org
  default_ec2_keyname: aws-eb
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running PHP 5.6
  default_region: us-east-1
  profile: eb-cli
  sc: git
